#!/bin/sh

tmux new-session -s 'ai-generator' -c "$HOME/Documents/Projects/ai-generator/" \; \
    send-keys 'n' C-m \; \
    new-window -c "$HOME/Documents/Projects/ai-generator/" \; \
    send-keys "lg" C-m \; \
    new-window -c "$HOME/Documents/Projects/ai-generator/ui" \; \
    send-keys '' C-m \; \
    new-window -c "$HOME/Documents/Projects/ai-generator/" \; \
    select-window -t 1 \;
