#!/bin/sh

tmux new-session -s 'codecannon' -c "$HOME/Documents/Projects/codedjen2/" \; \
    send-keys 'n' C-m \; \
    new-window -c "$HOME/Documents/Projects/codedjen2/" \; \
    send-keys "lg" C-m \; \
    new-window -c "$HOME/Documents/Projects/codedjen2" \; \
    send-keys 'ddd' C-m \; \
    select-window -t 1 \;
