#!/bin/sh

tmux new-session -s 'codecannon-ai-2' -c "$HOME/Documents/Projects/codecannon2/" \; \
    send-keys 'n' C-m \; \
    new-window -c "$HOME/Documents/Projects/codecannon2/" \; \
    send-keys "lg" C-m \; \
    new-window -c "$HOME/Documents/Projects/codecannon2" \; \
    send-keys 'opencode' C-m \; \
    select-window -t 1 \;
