#!/bin/sh

tmux new-session -s 'codedjen' -c "$HOME/Documents/Projects/codedjen/" \; \
    send-keys 'n' C-m \; \
    new-window -c "$HOME/Documents/Projects/codedjen/" \; \
    send-keys "lg" C-m \; \
    new-window -c "$HOME/Documents/Projects/codedjen/ui" \; \
    send-keys 'bun dev' C-m \; \
    new-window -c "$HOME/Documents/Projects/codedjen/api" \; \
    send-keys 'php artisan serve' C-m \; \
    new-window -c "$HOME/Documents/Projects/codedjen/" \; \
    select-window -t 1 \;
