#!/bin/sh

tmux new-session -s 'LedinskeKlasike.si' -c "$HOME/Documents/Projects/LedinskeKlasike.si/" \; \
    send-keys 'n' C-m \; \
    new-window -c "$HOME/Documents/Projects/LedinskeKlasike.si/" \; \
    send-keys "lg" C-m \; \
    new-window -c "$HOME/Documents/Projects/LedinskeKlasike.si/" \; \
    send-keys 'yarn dev' C-m \; \
    new-window -c "$HOME/Documents/Projects/LedinskeKlasike.si/" \; \
    select-window -t 1 \;
