#!/bin/sh

tmux new-session -s 'MindForge' -c "$HOME/Documents/Projects/MindForge/" \; \
    send-keys 'n' C-m \; \
    new-window -c "$HOME/Documents/Projects/MindForge/frontend/" \; \
    send-keys 'yarn dev' C-m \; \
    new-window -c "$HOME/Documents/Projects/MindForge/" \; \
    send-keys "lg" C-m \; \
    new-window -c "$HOME/Documents/Projects/MindForge/" \; \
    select-window -t 1 \;
