#!/bin/sh

tmux new-session -s 'Tomaz.co' -c "$HOME/Documents/Projects/Tomaz.co/" \; \
    send-keys 'n' C-m \; \
    new-window -c "$HOME/Documents/Projects/Tomaz.co/" \; \
    send-keys "lg" C-m \; \
    new-window -c "$HOME/Documents/Projects/Tomaz.co/" \; \
    send-keys 'yarn dev' C-m \; \
    new-window -c "$HOME/Documents/Projects/Tomaz.co/" \; \
    select-window -t 1 \;
